version: '3'

services:
  # postgreSQL:
  #   container_name: pg_container
  #   image: postgres
  #   restart: always
  #   volumes:
  #     - ./db/:/var/lib/postgresql
  #     - ./db/data:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_USER: root
  #     POSTGRES_PASSWORD: root
  #     POSTGRES_DB: test_db
  #   networks:
  #     eiei:
  #       ipv4_address: 172.20.0.4 
  #   ports:
  #     - "5432:5432"

  # pgadmin:
  #   container_name: pgadmin4_container
  #   image: dpage/pgadmin4
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: root
  #   ports:
  #     - "5050:80"
  #   networks:
  #     - eiei
  iq180_backend:
    container_name: iq180_backend
    restart: on-failure
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    networks:
      - eiei
    command: >
      sh -c "apk add --no-cache npm &&
      daphne core.asgi:application -b 0.0.0.0 -p 8000"
  redis:
    container_name: redis
    image: redis:5
    ports:
      - 6379:6379
    networks:
      - eiei
    restart: on-failure

networks:
  eiei:
    name: eiei
    ipam:
      config:
        - subnet: 172.20.0.0/16 # Define a subnet for the custom network